const adviceList = [
    "Comienza despacio y enfócate en la técnica.",
    "Hidrátate regularmente a lo largo del día.",
    "Incluye ejercicios compuestos en tu rutina.",
    "Aumenta el peso gradualmente para evitar lesiones.",
    "Mantén una dieta equilibrada con suficiente proteína.",
    "Aprende la forma correcta de cada ejercicio.",
    "Usa el peso corporal antes de añadir pesas.",
    "Sé constante con tus entrenamientos.",
    "Toma al menos un día de descanso entre entrenamientos.",
    "Calienta adecuadamente antes de cada sesión.",
    "Estira después de cada entrenamiento para mejorar la flexibilidad.",
    "Enfócate en entrenamientos de cuerpo completo para ganar fuerza general.",
    "Aumenta la intensidad gradualmente para evitar estancamientos.",
    "Varía tu rutina para desafiar diferentes grupos musculares.",
    "Registra tu progreso en un diario de entrenamiento.",
    "El descanso es tan importante como el entrenamiento.",
    "Entrena tu core para mejorar la estabilidad y prevenir lesiones.",
    "Usa bandas de resistencia para añadir variedad a tus entrenamientos.",
    "Incorpora cardio para mejorar tu estado físico y resistencia.",
    "Comienza con sesiones cortas y efectivas (30-45 minutos).",
    "No tengas miedo de pedir ayuda o asesoría.",
    "Asegúrate de usar calzado adecuado durante el ejercicio.",
    "Escucha a tu cuerpo; detente si algo se siente mal.",
    "Concéntrate en la calidad de cada repetición en lugar de la cantidad.",
    "Practica técnicas de respiración durante los ejercicios.",
    "Incorpora yoga o Pilates para mejorar la flexibilidad y el equilibrio.",
    "Consume suficientes calorías para alimentar tus entrenamientos.",
    "Planifica tus comidas para evitar elecciones poco saludables.",
    "Incluye frutas y verduras en cada comida.",
    "Evita los alimentos ultraprocesados tanto como sea posible.",
    "Desayuna para tener energía al comenzar el día.",
    "Come después de entrenar para ayudar en la recuperación.",
    "Evita saltarte comidas, especialmente después de entrenar.",
    "Consume carbohidratos complejos para obtener energía sostenida.",
    "Mantén un equilibrio entre carbohidratos, proteínas y grasas saludables.",
    "Controla las porciones para evitar comer en exceso.",
    "Incluye fuentes de fibra para mejorar la digestión.",
    "Evita el azúcar refinado y los alimentos con muchas calorías vacías.",
    "Bebe suficiente agua, al menos 8 vasos al día.",
    "No sigas dietas restrictivas; enfócate en una alimentación equilibrada.",
    "Planifica tus días de entrenamiento y comidas con antelación.",
    "Siéntete cómodo con la alimentación intuitiva: come cuando tengas hambre.",
    "No te obsesiones con los números de la báscula; enfócate en cómo te sientes.",
    "Establece metas realistas y a largo plazo.",
    "Equilibra los entrenamientos de fuerza con sesiones de movilidad y estiramiento.",
    "Prueba diferentes tipos de entrenamiento para encontrar lo que más te gusta.",
    "Sé paciente con los resultados; las ganancias requieren tiempo.",
    "Aprende a identificar la diferencia entre el dolor bueno (esfuerzo) y el malo (lesión).",
    "Rodéate de personas que apoyen tus objetivos de salud y fitness.",
    "Mantén una actitud positiva y disfruta el proceso."
];


export default adviceList; 